// Generates src/styles/tokens.css from the `colors:` block of DESIGN.md (single source of truth
// for the palette) plus the few role tokens DESIGN.md describes only in prose.
// Run: npm run tokens -w @budget/ui   (the unit test fails when the committed file is stale)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

/** Read `key: "value"` pairs of the frontmatter block `colors:`. */
export function parseColors(designMd) {
  const frontmatter = /^---\n([\s\S]*?)\n---/.exec(designMd)?.[1] ?? '';
  const block = /^colors:\n((?: {2}.+\n?)+)/m.exec(frontmatter)?.[1] ?? '';
  const colors = {};
  for (const line of block.split('\n')) {
    const m = /^ {2}([\w-]+): "(#[0-9a-fA-F]{6})"/.exec(line);
    if (m) colors[m[1]] = m[2].toLowerCase();
  }
  return colors;
}

// Roles that DESIGN.md names in prose only (tints, scrim, shadow, direction colours, dark hover).
const EXTRA = {
  light: {
    'red-soft': 'rgba(196, 42, 31, 0.08)',
    tint: 'rgba(23, 71, 166, 0.06)',
    'tint-2': 'rgba(23, 71, 166, 0.11)',
    overlay: 'rgba(11, 27, 51, 0.32)',
    shadow: '0 10px 22px -10px rgba(11, 27, 51, 0.30), 0 2px 5px rgba(11, 27, 51, 0.08)',
    'heat-red': '#f3b3a9',
    'heat-green': '#a9dbb8',
    'good-ink': '#2d7a4c',
    'bad-ink': '#b0463a',
    'heat-max': '44%',
    'on-red': '#ffffff',
  },
  dark: {
    'primary-hover': '#ffffff',
    'red-soft': 'rgba(255, 139, 123, 0.12)',
    tint: 'rgba(210, 236, 255, 0.07)',
    'tint-2': 'rgba(210, 236, 255, 0.13)',
    overlay: 'rgba(4, 14, 32, 0.55)',
    shadow: '0 12px 24px -10px rgba(2, 10, 26, 0.7), 0 2px 6px rgba(2, 10, 26, 0.4)',
    'heat-red': '#b8665d',
    'heat-green': '#4f9a6c',
    'good-ink': '#8fd6a8',
    'bad-ink': '#f2a497',
    'heat-max': '34%',
    'on-red': '#1a0d0b',
  },
};

/** Role order in the output; every role must exist for light and dark. */
const ROLES = [
  'ground',
  'ground-2',
  'raised',
  'ink',
  'ink-2',
  'ink-3',
  'line',
  'line-2',
  'rule',
  'rule-strong',
  'graticule',
  'primary',
  'primary-hover',
  'on-primary',
  'red',
  'red-soft',
  'on-red',
  'need',
  'want',
  'future',
  'tint',
  'tint-2',
  'overlay',
  'shadow',
  'heat-red',
  'heat-green',
  'good-ink',
  'bad-ink',
  'heat-max',
];

function modeValues(colors, mode) {
  const values = {};
  for (const role of ROLES) {
    const fromDesign = mode === 'dark' ? colors[`dark-${role}`] : colors[role];
    const value =
      fromDesign ?? EXTRA[mode][role] ?? (mode === 'dark' ? undefined : EXTRA.light[role]);
    if (value === undefined) throw new Error(`Token "${role}" (${mode}) is missing in DESIGN.md`);
    values[role] = value;
  }
  return values;
}

const declarations = (values, indent) =>
  ROLES.map((role) => `${indent}--${role}: ${values[role]};`).join('\n');

export function generateTokensCss(designMd) {
  const colors = parseColors(designMd);
  const light = modeValues(colors, 'light');
  const dark = modeValues(colors, 'dark');
  return `/* GENERATED by scripts/generate-tokens.mjs from DESIGN.md. Do not edit by hand. */

/* Light: blue ink on white drafting film. */
:root {
  color-scheme: light;
${declarations(light, '  ')}
}

/* Dark: classic blueprint. Follows the system unless a theme is forced with data-theme. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${declarations(dark, '    ')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${declarations(dark, '  ')}
}

/* Print always uses the light tokens (the doubled specificity beats the theme selectors). */
@media print {
  :root:not(#_),
  :root[data-theme]:not(#_) {
    color-scheme: light;
${declarations(light, '    ')}
  }
}
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const designMd = readFileSync(here('../../../DESIGN.md'), 'utf8');
  writeFileSync(here('../src/styles/tokens.css'), generateTokensCss(designMd));
  console.log('Wrote packages/ui/src/styles/tokens.css');
}
