import type { VerdictFactType, VerdictTemplate } from './verdicts';

type Tone = VerdictTemplate['tone'];
type Line = readonly [Tone, string];
const s = (text: string): Line => ['sachlich', text];
const a = (text: string): Line => ['anerkennend', text];
const h = (text: string): Line => ['trocken-humorvoll', text];
const w = (text: string): Line => ['warnend', text];

/**
 * Each line is a complete, reviewed sentence in one voice ("dein"); the tone is part of the line.
 * Identifiers stay stable when appending. `{month}: ` only ever opens a sentence (it is dropped
 * for multi-month periods); odd and even positions form the two parity banks.
 */
const bank: Record<VerdictFactType, readonly Line[]> = {
  'record-high': [
    s('{month}: {label} {amount} ist der {rank} Monat {scope}.'),
    a('{month}: Mit {amount} ist {label} dein {rank} Monat {scope}.'),
    s('{month}: {label} {amount} ergibt Rang {n} {scope}.'),
    a('{month}: {label} {amount} – dein {rank} Monat {scope}, das kann sich sehen lassen.'),
    s('{month}: {label} steht bei {amount} und belegt Rang {n} {scope}.'),
    a('{month}: Das ist dein {rank} Monat {scope}: {label} {amount}.'),
    s('{month}: {label} {amount} gehört {scope} zu den drei {strongest} Monaten.'),
    a('{month}: Rang {n} {scope} – {label} erreicht {amount}.'),
    h('{month}: {label} {amount} – in deinen Aufzeichnungen steht dieser Monat weit vorne.'),
    a('{month}: {label} {amount} reiht sich als {rank} Monat {scope} ein.'),
  ],
  'record-low': [
    w('{month}: {label} {amount} – der {worst} Monat {scope}; prüfe die Ursachen.'),
    s('{month}: Mit {amount} ist {label} der {worst} Monat {scope}.'),
    w('{month}: {label} {amount} – so ungünstig war kein Monat {scope}.'),
    w('{month}: {label} steht bei {amount}, dem ungünstigsten Stand {scope}; prüfe die Treiber.'),
    s('{month}: {label} {amount} ist der {worst} Monat {scope}, kein Urteil über dich.'),
    w('{month}: {label} {amount} liegt hinter allen anderen Monaten {scope}.'),
    w('{month}: {label} {amount} – ein Anlass, die größten Posten durchzugehen.'),
    w('{month}: {label} {amount}; die Einzelwerte zeigen, was diesen Monat belastet hat.'),
    s(
      '{month}: {label} {amount} fällt {scope} am ungünstigsten aus; die Zeitreihe zeigt den Verlauf.',
    ),
    w('{month}: {label} {amount} – ein ungünstiger Monat, aber kein Grund zur Panik.'),
  ],
  'streak-savings': [
    s('{month}: Seit {n} Monaten liegt deine Sparquote bei mindestens {threshold}.'),
    a('{n} Monate in Folge erreicht deine Sparquote mindestens {threshold}.'),
    a('{month}: {n} Monate mit mindestens {threshold} Sparquote – dein Ziel bleibt erreicht.'),
    s('{month}: Deine Sparquote hält seit {n} Monaten die Marke von {threshold}.'),
    a('{n} Monate hintereinander mindestens {threshold} Sparquote – das zahlt sich aus.'),
    a('{month}: Deine Reihe wächst auf {n} Monate mit mindestens {threshold} Sparquote.'),
    s('{month}: Zum {n}. Mal in Folge liegt deine Sparquote bei {threshold} oder darüber.'),
    a('{month}: {n} Monate auf oder über deinem Ziel von {threshold} – das ist Verlässlichkeit.'),
    a('{month}: Seit {n} Monaten schaffst du mindestens {threshold} Sparquote; die Routine trägt.'),
    h('{month}: {n} Monate mindestens {threshold} Sparquote – Routine darf ruhig langweilig sein.'),
  ],
  'streak-budget': [
    s('{month}: {n} Monate in Folge bleiben deine Ausgaben im Plan.'),
    a('{month}: Dein Plan hält seit {n} Monaten.'),
    s('{n} Monate hintereinander im Plan – dieser Zeitraum gehört dazu.'),
    s('{month}: Zum {n}. Mal in Folge bleiben die Ausgaben im Plan.'),
    s('{month}: Seit {n} Monaten reichen deine geplanten Beträge.'),
    a('{month}: {n} Monate ohne Planüberschreitung – deine Planung trägt.'),
    s('{month}: Die Reihe der Monate im Plan wächst auf {n}.'),
    h('{month}: {n} Monate im Plan; Beständigkeit muss nicht aufregend sein.'),
    a('{month}: Dein Plan bewährt sich den {n}. Monat hintereinander.'),
    s('{month}: {n} Monate im Plan, ohne dass eine Kategorie überzogen wurde.'),
  ],
  'streak-wealth': [
    s('{month}: Dein Nettovermögen steigt den {n}. Monat in Folge.'),
    a('{n} Monate hintereinander wächst dein Nettovermögen – dieser Zeitraum gehört dazu.'),
    s('{month}: Seit {n} Monaten wächst dein Nettovermögen.'),
    s('{month}: Die Reihe positiver Vermögensmonate erreicht {n}.'),
    a('{month}: {n} Monate mit Vermögenszuwachs; die Richtung bleibt aufwärts.'),
    s('{month}: Dein Nettovermögen legt seit {n} Monaten Monat für Monat zu.'),
    s('{month}: Zum {n}. Mal hintereinander steht mehr Nettovermögen am Monatsende.'),
    a('{month}: {n} positive Vermögensmonate in Folge – ein beständiger Verlauf.'),
    s('{month}: Dein Nettovermögen liegt seit {n} Monaten über dem jeweiligen Vormonat.'),
    h('{month}: {n} Monate Vermögenszuwachs – die Kurve geht weiter die Treppe hinauf.'),
  ],
  'comparison-up': [
    s('{month}: {label} liegt bei {current}, {amount} mehr als im {reference}.'),
    s('{month}: {label} liegt bei {current} und damit {amount} über dem {reference}.'),
    s('{month}: {label} {current} – ein Plus von {amount} gegenüber {reference}.'),
    s('{month}: {label} {current}, das sind {amount} mehr als {reference}.'),
    s('{month}: {label} steigt gegenüber {reference} um {amount} auf {current}.'),
    s('{month}: {label} übertrifft {reference} um {amount} und steht bei {current}.'),
    s('{month}: Gegenüber {reference} liegt {label} um {amount} höher, bei {current}.'),
    s('{month}: {label} steht bei {current}, {amount} höher als {reference}.'),
    s(
      '{month}: Mit {current} liegt {label} {amount} über {reference}; die Details zeigen die Treiber.',
    ),
    s('{month}: {label} {current} – im Vergleich zu {reference} sind das {amount} mehr.'),
  ],
  'comparison-down': [
    s('{month}: {label} liegt bei {current}, {amount} weniger als im {reference}.'),
    s('{month}: {label} liegt bei {current} und damit {amount} unter dem {reference}.'),
    s('{month}: {label} {current} – ein Minus von {amount} gegenüber {reference}.'),
    s('{month}: {label} {current}, das sind {amount} weniger als {reference}.'),
    s('{month}: {label} sinkt gegenüber {reference} um {amount} auf {current}.'),
    s('{month}: {label} unterschreitet {reference} um {amount} und steht bei {current}.'),
    s('{month}: Gegenüber {reference} liegt {label} um {amount} niedriger, bei {current}.'),
    s('{month}: {label} steht bei {current}, {amount} niedriger als {reference}.'),
    s(
      '{month}: Mit {current} liegt {label} {amount} unter {reference}; die Details zeigen die Treiber.',
    ),
    s('{month}: {label} {current} – im Vergleich zu {reference} sind das {amount} weniger.'),
  ],
  'threshold-wealth': [
    a('{month}: Dein Nettovermögen hat die Marke von {amount} erreicht.'),
    a('{month}: Erstmals in diesem Vergleich liegt dein Nettovermögen bei mindestens {amount}.'),
    s('{month}: Die Marke von {amount} Nettovermögen ist erreicht oder überschritten.'),
    a('{month}: Dein Nettovermögen überschreitet {amount} – ein Meilenstein in diesem Vergleich.'),
    a('{month}: {amount} Nettovermögen sind erreicht, eine runde Marke auf deinem Weg.'),
    s('{month}: Dein Nettovermögen liegt nun auf oder über {amount}.'),
    a('{month}: Dein Nettovermögen hat bei {amount} eine neue runde Marke passiert.'),
    s('{month}: Deine Vermögenslinie erreicht die Schwelle von {amount}.'),
    a('{month}: Du hast mindestens {amount} Nettovermögen erreicht.'),
    h('{month}: {amount} Nettovermögen – eine runde Zahl, die sich sehen lassen kann.'),
  ],
  'threshold-emergency': [
    a('{month}: Dein Notgroschen reicht jetzt für mindestens {n} {months}.'),
    s('{month}: Mit dem Notgroschen ist Bedarf für mindestens {n} {months} gedeckt.'),
    a('{month}: Dein Notgroschen reicht für {n} {months} – eine neue Schwelle ist erreicht.'),
    s('{month}: Deine Reserve trägt nun mindestens {n} {months} Bedarf.'),
    a('{month}: Notgroschen für {n} {months} erreicht – dein Puffer wächst.'),
    s('{month}: Dein Notgroschen erreicht nun mindestens {n} {months} Reichweite.'),
    s('{month}: Der Notgroschen sichert jetzt mindestens {n} {months} ab.'),
    s('{month}: Die Reichweite deiner Reserve beträgt mindestens {n} {months}.'),
    a('{month}: {n} {months} Bedarf sind aus der Reserve gedeckt – ein zusätzlicher Puffer.'),
    h('{month}: Dein Notgroschen trägt mindestens {n} {months}; die Reserve kann durchatmen.'),
  ],
  'debt-down': [
    a('{month}: Deine Schulden sind um {amount} gesunken.'),
    a('{month}: {amount} weniger Schulden – die offene Summe wird kleiner.'),
    a('{month}: Du hast deine Schuldenlast um {amount} verringert.'),
    s('{month}: Dein Schuldenstand liegt {amount} unter dem vorherigen Stand.'),
    a('{month}: Deine offene Schuld ist um {amount} kleiner geworden.'),
    s('{month}: Beim Schuldenstand sind {amount} abgebaut.'),
    a('{month}: {amount} Schulden weniger; dieser Fortschritt bleibt sichtbar.'),
    s('{month}: Deine Schuldenlinie fällt um {amount}.'),
    a('{month}: Dein Schuldenstand sinkt um {amount} – ein Schritt Richtung Entlastung.'),
    h('{month}: {amount} weniger Schulden – diese Zahl darf gern weiter schrumpfen.'),
  ],
  'market-up': [
    a('{month}: Der Markt arbeitet für dich: {amount} positiver Markteffekt.'),
    a('{month}: {amount} kommen aus dem Markt – das stützt dein Vermögen.'),
    s('{month}: Der Markteffekt beträgt plus {amount}.'),
    s('{month}: Der Markt steuert {amount} zum Wertzuwachs bei.'),
    a('{month}: Der Markt wirkt für dich mit {amount}.'),
    s('{month}: Der positive Marktbeitrag beträgt {amount}.'),
    s('{month}: Die Marktbewegung bringt {amount}; deine eigenen Beiträge bleiben getrennt.'),
    a('{month}: {amount} Marktzuwachs – der Markt hilft diesmal mit.'),
    s('{month}: Der Markt hebt deinen Wert um {amount}.'),
    h('{month}: {amount} vom Markt – Rückenwind nimmst du gern mit.'),
  ],
  'market-down': [
    w('{month}: Der Markt wirkt gegen dich: {amount} negativer Markteffekt.'),
    w('{month}: {amount} gehen auf den Markt zurück; sieh die Entwicklung im Zusammenhang.'),
    s('{month}: Der Markteffekt beträgt minus {amount}.'),
    s('{month}: Die Marktbewegung mindert deinen Wert um {amount}.'),
    w('{month}: Der Markt wirkt gegen dich, der Rückgang beträgt {amount}.'),
    s('{month}: Der negative Marktbeitrag beträgt {amount}.'),
    s('{month}: {amount} Marktverlust; deine eigenen Einzahlungen bleiben davon getrennt.'),
    w('{month}: Der Markt drückt deinen Wert um {amount}; das ist kein Urteil über deinen Plan.'),
    s('{month}: {amount} Rückgang durch den Markt; die Zeitreihe liefert den Zusammenhang.'),
    w('{month}: {amount} Gegenwind vom Markt; ein ruhiger Blick auf den Verlauf hilft.'),
  ],
  effort: [
    a('{month}: Dein eigener Beitrag von {amount} überwiegt den negativen Markteffekt.'),
    a('{month}: {amount} eigener Beitrag – mehr, als der Markt wieder genommen hat.'),
    a('{month}: Trotz Marktverlust trägt dein eigener Beitrag von {amount} stärker.'),
    s('{month}: Dein Beitrag von {amount} ist größer als der Rückgang durch den Markt.'),
    a('{month}: {amount} aus eigener Kraft übertreffen den Marktverlust.'),
    s('{month}: Der Markt bremst, dein eigener Beitrag von {amount} wiegt schwerer.'),
    s('{month}: Dein Beitrag beträgt {amount} und gleicht den Marktrückgang mehr als aus.'),
    a('{month}: Dein eigener Beitrag von {amount} trägt über den Marktverlust hinaus.'),
    s('{month}: Gegenwind vom Markt, aber dein eigener Beitrag ist stärker: {amount}.'),
    h('{month}: Dein Beitrag von {amount} war stärker als der Gegenwind vom Markt.'),
  ],
  'rule-bad': [
    w('{month}: {n} {rules} verletzt – die Befunde zeigen, wo du ansetzen kannst.'),
    w('{month}: {n} {rules} {verb} Aufmerksamkeit; beginne bei den konkreten Befunden.'),
    w('{month}: Bei {n} {rules} ist die Grenze verletzt; prüfe die nächsten Schritte.'),
    s('{month}: Der Finanz-Check meldet {n} verletzte {rules}.'),
    w('{month}: {n} {rules} liegen außerhalb der Grenze – ein Anlass zum Prüfen.'),
    w('{month}: Für {n} {rules} steht eine Korrektur an; die Befunde erklären warum.'),
    w('{month}: {n} verletzte {rules}; ein Schritt nach dem anderen reicht als Anfang.'),
    s('{month}: {n} {rules} verletzt – der Finanz-Check liefert Ansatzpunkte.'),
    s('{month}: Die Regelprüfung zeigt {n} Verletzungen; sieh dir die Ursachen an.'),
    w('{month}: {n} {rules} verletzt – eine Bestandsaufnahme, kein persönliches Urteil.'),
  ],
  'rule-warn': [
    w('{month}: {n} {rules} mit Warnung – die Grenzen verdienen einen Blick.'),
    s('{month}: Der Finanz-Check warnt bei {n} {rules}.'),
    w('{month}: {n} {rules} liegen im Warnbereich; prüfe den Spielraum.'),
    w('{month}: Für {n} {rules} besteht eine Warnung; die Befunde zeigen mehr.'),
    w('{month}: Es gibt {n} Regelwarnungen – ein guter Zeitpunkt, die Ursachen anzusehen.'),
    s('{month}: Die Prüfung zeigt Warnungen bei {n} {rules}.'),
    w('{month}: {n} {rules} liegen im Warnbereich; behalte die Entwicklung im Blick.'),
    w('{month}: Warnstufe bei {n} {rules}; prüfe die konkreten Hinweise.'),
    s('{month}: {n} {rules} geben ein Warnsignal; die Details helfen beim Einordnen.'),
    w('{month}: {n} {rules} mit Warnung – der Finanz-Check meldet sich rechtzeitig.'),
  ],
  'rule-ok': [
    a('{month}: Der Finanz-Check bestätigt {n} erfüllte {rules}.'),
    s('{month}: {n} {rules} bewertet – die Prüfung zeigt keine Verletzung.'),
    a('{month}: Der Finanz-Check zeigt {n} erfüllte {rules} und keine Warnung.'),
    s('{month}: {n} {rules} geprüft, alle bewerteten Grenzen halten.'),
    a('{month}: Der Finanz-Check bleibt bei {n} bewerteten {rules} im grünen Bereich.'),
    s('{month}: {n} erfüllte {rules} – die bewerteten Grundlagen passen.'),
    s('{month}: Die Prüfung meldet bei {n} {rules} weder Warnung noch Verletzung.'),
    s('{month}: Die Auswertung enthält {n} bewertete {rules}, ohne Warnung und ohne Verletzung.'),
    a('{month}: Die Regelprüfung bestätigt {n} erfüllte {rules}.'),
    h('{month}: {n} bewertete {rules} erfüllt – der Finanz-Check hat wenig zu melden.'),
  ],
  milestone: [
    a('{month}: Das ist dein erster aufgezeichneter Monat ohne Planüberschreitung.'),
    a('{month}: Zum ersten Mal seit Aufzeichnungsbeginn bleiben die Ausgaben im Plan.'),
    a('{month}: Erstmals überschreitest du den Plan nicht – ein neuer Meilenstein.'),
    s('{month}: Der erste Monat im Plan ist erreicht.'),
    a('{month}: Dein Plan hält erstmals über einen vollständigen Monat.'),
    a('{month}: Ein erster vollständiger Monat ohne Planüberschreitung ist geschafft.'),
    s('{month}: Die Aufzeichnungen zeigen erstmals einen Monat im Plan.'),
    s('{month}: Erstmals reicht der Plan für den ganzen Monat.'),
    s('{month}: Der erste Monat ohne Planüberschreitung steht in deiner Zeitreihe.'),
    h('{month}: Zum ersten Mal ohne Planüberschreitung – das verdient ein Häkchen.'),
  ],
  'category-streak': [
    s('{month}: {category} bleibt seit {n} Monaten im Plan.'),
    a('{month}: {category} bleibt {n} Monate in Folge ohne Planüberschreitung.'),
    s('{month}: Bei {category} hält dein Plan den {n}. Monat hintereinander.'),
    s('{month}: Für {category} reichen die geplanten Beträge seit {n} Monaten.'),
    s('{month}: {category} liegt seit {n} Monaten auf oder unter dem Plan.'),
    a('{month}: Die Reihe für {category} wächst auf {n} Monate im Plan.'),
    a('{month}: {n} Monate bei {category} im Plan – eine beständige Reihe.'),
    s('{month}: Seit {n} Monaten passen bei {category} Ausgaben und Plan zusammen.'),
    a('{month}: Auch {category} hält den Plan, zum {n}. Mal in Folge.'),
    h('{month}: {category} hält seit {n} Monaten den Plan und macht keinen Ärger.'),
  ],
  equivalent: [
    s('{month}: {label} {amount} entspricht {equivalent} {equivalentUnit} für {category}.'),
    s('{month}: {label} {amount} sind etwa {equivalent} {equivalentUnitNom} für {category}.'),
    s(
      '{month}: {label} {amount} sind, gemessen an {category}, rund {equivalent} {equivalentUnitNom}.',
    ),
    s(
      '{month}: {label} {amount} deckt rechnerisch {equivalent} {equivalentUnitNom} für {category}.',
    ),
    s(
      '{month}: Gemessen an {category} sind {amount} {label} rund {equivalent} {equivalentUnitNom}.',
    ),
    s(
      '{month}: {label} erreicht {amount}, das sind {equivalent} {equivalentUnitNom} für {category}.',
    ),
    s('{month}: Der Betrag {amount} entspricht {equivalent} {equivalentUnit} für {category}.'),
    s('{month}: {label} {amount} entspricht dem {equivalent}-Fachen deiner Kosten für {category}.'),
    s('{month}: {label} {amount} entsprechen {equivalent} {equivalentUnitNom} für {category}.'),
    s(
      '{month}: {equivalent} {equivalentUnitNom} für {category} – so lassen sich {amount} einordnen.',
    ),
  ],
  negative: [
    w('{month}: {label} {amount} – das Minus verdient einen Blick auf die Ursachen.'),
    w('{month}: {label} steht bei {amount}; prüfe die größten Treiber.'),
    w('{month}: {label} {amount} – ein Minus, das sich erklären lässt.'),
    w('{month}: {label} liegt mit {amount} unter null; die Details zeigen die Ursachen.'),
    w('{month}: {label} ist mit {amount} negativ; beginne mit den Einzelwerten.'),
    w('{month}: {label} {amount} – sieh dir die Entwicklung dieses Zeitraums an.'),
    w(
      '{month}: {label} {amount} – das ist eine ehrliche Bestandsaufnahme für den nächsten Schritt.',
    ),
    w('{month}: {label} beträgt {amount}; prüfe, was das Minus ausgelöst hat.'),
    w('{month}: {label} {amount} – prüfe die größten Treiber und plane den nächsten Schritt.'),
    w('{month}: {label} {amount} – die Zahl ist negativ, die Ursachen lassen sich prüfen.'),
  ],
  summary: [
    s('{month}: {label} {amount} – die Einzelwerte zeigen den Zusammenhang.'),
    s('{month}: Der ausgewiesene Wert für {label} beträgt {amount}.'),
    s('{month}: {label} steht bei {amount}; die Details ordnen den Wert ein.'),
    s('{month}: {label} liegt bei {amount}.'),
    s('{month}: Im Mittelpunkt steht {label} mit {amount}.'),
    s('{month}: {label} {amount}; für die Einordnung hilft der Verlauf.'),
    s('{month}: Die Auswertung zeigt {label} mit {amount}.'),
    s('{month}: {label} erreicht {amount}; dahinter stehen die aufgeführten Einzelwerte.'),
    s('{month}: {label} beträgt {amount} – das ist der Stand dieses Zeitraums.'),
    s('{month}: {label} {amount} – die Tabelle liefert die Einzelheiten dazu.'),
  ],
  unavailable: [
    s('{month}: Für ein belastbares Fazit fehlen vergleichbare Werte.'),
    s('{month}: Für diesen Report fehlt noch eine belastbare Vergleichsbasis.'),
    s('{month}: Die vorhandenen Daten reichen noch nicht für ein Zahlenfazit.'),
    s('{month}: Ein Fazit braucht vollständige Werte; die Vergleichsbasis ist noch offen.'),
    s('{month}: Ohne vergleichbare Werte bleibt das Fazit offen.'),
    s('{month}: Die Vergleichsbasis ist unvollständig; prüfe die Hinweise im Report.'),
    s('{month}: Für die Einordnung fehlen noch belastbare Zahlen.'),
    s('{month}: Die Datenbasis trägt derzeit keinen belastbaren Vergleich.'),
    s('{month}: Ein Zahlenfazit ist noch nicht möglich; die Datenhinweise zeigen, was fehlt.'),
    s('{month}: Das Fazit bleibt offen, bis die benötigten Werte vorliegen.'),
  ],
  neutral: [
    s('Die Einzelwerte geben den Überblick; ein besonderer Ausschlag ist nicht belegt.'),
    s('Die Einzelwerte helfen dir beim Einordnen dieses Zeitraums.'),
    s('Der Report zeigt den Zeitraum ohne besonderen Ausschlag.'),
    s('Die Details unten zeigen den Stand dieses Zeitraums.'),
    s('Der Zeitraum lässt sich anhand der aufgeführten Werte einordnen.'),
    s('Die Auswertung liefert den Überblick für diesen Zeitraum.'),
    s('Die Tabelle zeigt die Einzelheiten; ein besonderer Vergleich ist nicht belegt.'),
    s('Die Daten zeigen den Stand dieses Zeitraums.'),
    s('Im Zeitraum fällt nichts Besonderes auf; die Details stehen unten.'),
    s('Der Report ordnet die Werte ein, ohne eine Besonderheit zu behaupten.'),
  ],
};
export const VERDICT_TEMPLATES: readonly VerdictTemplate[] = Object.entries(bank).flatMap(
  ([type, lines]) =>
    lines.map(([tone, text], i) => ({
      id: `${type}-${i + 1}`,
      type: type as VerdictFactType,
      tone,
      text,
    })),
);
