import type { VerdictFactType, VerdictTemplate } from './verdicts';

/** Each line is a complete, reviewed sentence; identifiers remain stable when adding lines. */
const bank: Record<VerdictFactType, readonly string[]> = {
  'record-high': [
    '{month}: {label} {amount} – der {rank} Monat {scope}.',
    '{month}: Der {rank} Monat {scope} beim Wert {label}: {amount}.',
    '{label}: {amount} – {month} ist der {rank} Monat {scope}.',
    '{month} liegt beim Wert {label} auf Rang {n}: {amount}.',
    '{month}: {amount} beim Wert {label} – ein Spitzenmonat {scope}.',
    '{month}: {label} erreicht {amount} und damit einen vorderen Platz {scope}.',
    '{month}: {label} {amount} – dieser Monat gehört zu deinen stärksten {scope}.',
    '{month}: Mit {amount} beim Wert {label} steht dieser Monat weit vorne {scope}.',
    '{month}: {label} {amount} – die Aufzeichnungen haben einen neuen Spitzenplatz.',
    '{month}: {label} {amount} – der {rank} Monat; die Tabelle darf kurz staunen.',
  ],
  'record-low': [
    '{month}: {label} {amount} – der schwächste Monat {scope}; die Ursachen lohnen einen Blick.',
    '{month}: Beim Wert {label} sind {amount} der ungünstigste Stand {scope}.',
    '{month}: {label} {amount} – so schwach war kein Monat {scope}.',
    '{month}: {label} steht bei {amount}, der schwächste Vergleich {scope}; prüfe die Treiber.',
    '{month}: {amount} beim Wert {label} – der schwächste Vergleich {scope}, kein Urteil über dich.',
    '{label}: {amount} – {month} fällt schwächer aus als alle Vergleichsmonate.',
    '{month}: {label} {amount} – der bisher schwächste Vergleich; ein Anlass zum Nachsehen.',
    '{month}: {label} {amount} – der ungünstigste Vergleich; die Einzelwerte erklären mehr.',
    '{month}: {label} {amount} – dieser Vergleich verdient einen ruhigen Blick auf die Ursachen.',
    '{month}: {label} {amount} – die Zeitreihe zeigt einen schwachen Monat, keinen persönlichen Fehler.',
  ],
  'streak-savings': [
    '{month}: Seit {n} Monaten liegt deine Sparquote bei mindestens {threshold}.',
    '{n} Monate in Folge mindestens {threshold} Sparquote – eine beständige Reihe.',
    '{month}: {n} Monate mit mindestens {threshold} Sparquote; dein Ziel bleibt erreicht.',
    '{month}: Die Sparquote hält seit {n} Monaten die Marke von {threshold}.',
    '{n} Monate hintereinander mindestens {threshold} Sparquote – das zählt.',
    '{month}: Deine Reihe wächst auf {n} Monate mit mindestens {threshold} Sparquote.',
    '{month}: {threshold} Sparquote oder mehr, zum {n}. Mal hintereinander.',
    '{month}: {n} Monate Sparquote über oder auf {threshold} – Verlässlichkeit in Zahlen.',
    '{month}: Mindestens {threshold} Sparquote seit {n} Monaten; die Routine trägt.',
    '{month}: {n} Monate mindestens {threshold} Sparquote – die Tabelle kennt deine Routine.',
  ],
  'streak-budget': [
    '{month}: {n} Monate in Folge ohne Überschreitung des Plans.',
    '{month}: Dein Plan hält seit {n} Monaten; eine beständige Reihe.',
    '{n} Monate hintereinander im Plan – auch {month} gehört dazu.',
    '{month}: Zum {n}. Mal in Folge bleiben die Ausgaben im Plan.',
    '{month}: Seit {n} Monaten reichen die geplanten Beträge.',
    '{month}: {n} Monate ohne Planüberschreitung – die Planung trägt.',
    '{month}: Die Reihe der Monate im Plan wächst auf {n}.',
    '{month}: {n} Monate im Plan; Beständigkeit muss nicht aufregend sein.',
    '{month}: Dein Plan bewährt sich den {n}. Monat hintereinander.',
    '{month}: {n} Monate im Plan – die Tabelle hat wenig zu beanstanden.',
  ],
  'streak-wealth': [
    '{month}: Dein Nettovermögen steigt den {n}. Monat in Folge.',
    '{n} Monate hintereinander mehr Nettovermögen – auch {month} trägt dazu bei.',
    '{month}: Seit {n} Monaten wächst dein Nettovermögen.',
    '{month}: Die Reihe positiver Vermögensmonate erreicht {n}.',
    '{month}: {n} Monate mit Vermögenszuwachs; die Richtung bleibt aufwärts.',
    '{month}: Dein Nettovermögen legt seit {n} Monaten Monat für Monat zu.',
    '{month}: Zum {n}. Mal hintereinander steht mehr Nettovermögen am Monatsende.',
    '{month}: {n} positive Vermögensmonate in Folge – ein beständiger Verlauf.',
    '{month}: Nettovermögen seit {n} Monaten im Plus gegenüber dem jeweiligen Vormonat.',
    '{month}: {n} Monate Vermögenszuwachs – die Zeitreihe nimmt weiter die Treppe.',
  ],
  'comparison-up': [
    '{month}: {label} liegt {amount} über dem Vergleich {reference}.',
    '{month}: Beim Wert {label} sind es {amount} mehr als im Vergleich {reference}.',
    '{label}: Gegenüber {reference} kommen {amount} dazu.',
    '{month}: {amount} mehr beim Wert {label} gegenüber {reference}.',
    '{month}: {label} steigt gegenüber {reference} um {amount}.',
    '{month}: Der Abstand zu {reference} beträgt beim Wert {label} plus {amount}.',
    '{month}: {label} übertrifft den Vergleich {reference} um {amount}.',
    '{month}: Beim Wert {label} zeigt der Vergleich {reference} einen Zuwachs von {amount}.',
    '{month}: Gegenüber {reference} steht {label} um {amount} höher.',
    '{month}: {label} liegt um {amount} höher als bei {reference}; die Details erklären warum.',
  ],
  'comparison-down': [
    '{month}: {label} liegt {amount} unter dem Vergleich {reference}.',
    '{month}: Beim Wert {label} sind es {amount} weniger als im Vergleich {reference}.',
    '{label}: Gegenüber {reference} fehlen {amount} zum Vergleichswert.',
    '{month}: {amount} weniger beim Wert {label} gegenüber {reference}.',
    '{month}: {label} sinkt gegenüber {reference} um {amount}.',
    '{month}: Der Abstand zu {reference} beträgt beim Wert {label} minus {amount}.',
    '{month}: {label} unterschreitet den Vergleich {reference} um {amount}.',
    '{month}: Beim Wert {label} zeigt der Vergleich {reference} einen Rückgang von {amount}.',
    '{month}: Gegenüber {reference} steht {label} um {amount} niedriger.',
    '{month}: {label} liegt um {amount} niedriger als bei {reference}; die Details erklären warum.',
  ],
  'threshold-wealth': [
    '{month}: Dein Nettovermögen hat die Marke von {amount} erreicht.',
    '{month}: Erstmals in diesem Vergleich liegt dein Nettovermögen bei mindestens {amount}.',
    '{month}: Die Marke von {amount} Nettovermögen ist überschritten oder genau erreicht.',
    '{month}: Dein Nettovermögen passiert {amount} – ein neuer Meilenstein im Vergleich.',
    '{month}: {amount} Nettovermögen sind erreicht; eine runde Marke auf deinem Weg.',
    '{month}: Dein Nettovermögen liegt nun auf oder über {amount}.',
    '{month}: Bei {amount} hat dein Nettovermögen eine neue runde Marke passiert.',
    '{month}: Die Vermögenslinie erreicht die Schwelle von {amount}.',
    '{month}: Nettovermögen mindestens {amount} – die nächste runde Marke ist erreicht.',
    '{month}: {amount} Nettovermögen – eine runde Zahl darf kurz im Mittelpunkt stehen.',
  ],
  'threshold-emergency': [
    '{month}: Dein Notgroschen reicht jetzt für mindestens {n} {months}.',
    '{month}: Mit dem Notgroschen ist Bedarf für mindestens {n} {months} gedeckt.',
    '{month}: Dein Notgroschen reicht für {n} {months} – eine neue Schwelle ist erreicht.',
    '{month}: Die Reserve trägt nun mindestens {n} {months} Bedarf.',
    '{month}: Notgroschen für {n} {months} erreicht – dein Puffer wächst.',
    '{month}: Dein Notgroschen erreicht nun mindestens {n} {months} Reichweite.',
    '{month}: Der Notgroschen sichert jetzt mindestens {n} {months} ab.',
    '{month}: Die Reichweite deiner Reserve erreicht mindestens {n} {months}.',
    '{month}: {n} {months} Bedarf aus der Reserve – ein zusätzlicher Puffer.',
    '{month}: Der Notgroschen trägt mindestens {n} {months}; die Reserve kann durchatmen.',
  ],
  'debt-down': [
    '{month}: Deine Schulden sind um {amount} gesunken.',
    '{month}: {amount} weniger Schulden – die offene Summe wird kleiner.',
    '{month}: Du hast die Schuldenlast um {amount} verringert.',
    '{month}: Der Schuldenstand liegt {amount} unter dem vorherigen Stand.',
    '{month}: Deine offene Schuld ist um {amount} kleiner geworden.',
    '{month}: Beim Schuldenstand sind {amount} abgebaut.',
    '{month}: {amount} Schulden weniger; dieser Fortschritt bleibt sichtbar.',
    '{month}: Die Schuldenlinie fällt um {amount}.',
    '{month}: Dein Schuldenstand sinkt um {amount} – ein Schritt Richtung Entlastung.',
    '{month}: {amount} weniger Schulden – eine Zahl, die gerne kleiner werden darf.',
  ],
  'market-up': [
    '{month}: Der Markt arbeitet für uns: {amount} positiver Markteffekt.',
    '{month}: {amount} kommen aus dem Markt – Rückenwind für dein Vermögen.',
    '{month}: Der Markteffekt beträgt plus {amount}.',
    '{month}: Der Markt steuert {amount} zum Wertzuwachs bei.',
    '{month}: Markt für uns – der Beitrag liegt bei {amount}.',
    '{month}: Der positive Marktbeitrag erreicht {amount}.',
    '{month}: Die Marktbewegung bringt {amount}; eigene Beiträge bleiben getrennt.',
    '{month}: {amount} Marktzuwachs – der Markt hat mitgeholfen.',
    '{month}: Der Markt hebt den Wert um {amount}.',
    '{month}: {amount} vom Markt – Rückenwind muss man nicht selbst erzeugen.',
  ],
  'market-down': [
    '{month}: Der Markt arbeitet gegen uns: {amount} negativer Markteffekt.',
    '{month}: {amount} gehen auf den Markt zurück; prüfe die Entwicklung im Zusammenhang.',
    '{month}: Der Markteffekt beträgt minus {amount}.',
    '{month}: Die Marktbewegung mindert den Wert um {amount}.',
    '{month}: Markt gegen uns – der Rückgang liegt bei {amount}.',
    '{month}: Der negative Marktbeitrag erreicht {amount}.',
    '{month}: {amount} Marktverlust; eigene Einzahlungen bleiben davon getrennt.',
    '{month}: Der Markt drückt den Wert um {amount}; das ist kein Urteil über deinen Plan.',
    '{month}: {amount} Rückgang durch den Markt – die Zeitreihe gibt den Zusammenhang.',
    '{month}: {amount} Gegenwind vom Markt; ein ruhiger Blick auf den Verlauf hilft.',
  ],
  effort: [
    '{month}: Dein eigener Beitrag von {amount} überwiegt den negativen Markteffekt.',
    '{month}: {amount} eigener Beitrag – mehr als der Markt wieder genommen hat.',
    '{month}: Trotz Marktverlust trägt dein eigener Beitrag von {amount} stärker.',
    '{month}: Dein Beitrag von {amount} ist größer als der Rückgang durch den Markt.',
    '{month}: {amount} aus eigener Kraft übertreffen den Marktverlust.',
    '{month}: Der Markt bremst, dein eigener Beitrag von {amount} wiegt schwerer.',
    '{month}: Dein Beitrag erreicht {amount} und gleicht mehr als den Marktrückgang aus.',
    '{month}: Der eigene Beitrag von {amount} trägt über den Marktverlust hinaus.',
    '{month}: Gegenwind vom Markt, stärkerer eigener Beitrag: {amount}.',
    '{month}: Dein Beitrag von {amount} war stärker als der Gegenwind vom Markt.',
  ],
  'rule-bad': [
    '{month}: {n} {rules} verletzt – die Befunde zeigen, wo du ansetzen kannst.',
    '{month}: {n} {rules} {verb} Aufmerksamkeit; beginne bei den konkreten Befunden.',
    '{month}: Bei {n} {rules} ist die Grenze verletzt; prüfe die nächsten Schritte.',
    '{month}: Der Finanz-Check meldet {n} verletzte {rules}.',
    '{month}: {n} {rules} außerhalb der Grenze – ein Anlass zum Prüfen.',
    '{month}: Für {n} {rules} steht eine Korrektur an; die Befunde erklären warum.',
    '{month}: {n} verletzte {rules}; ein Schritt nach dem anderen reicht als Anfang.',
    '{month}: {n} {rules} verletzt – der Finanz-Check liefert Ansatzpunkte.',
    '{month}: Die Regelprüfung zeigt {n} Verletzungen; sieh dir die Ursachen an.',
    '{month}: {n} {rules} verletzt – eine Bestandsaufnahme, kein persönliches Urteil.',
  ],
  'rule-warn': [
    '{month}: {n} {rules} mit Warnung – die Grenzen verdienen einen Blick.',
    '{month}: Der Finanz-Check warnt bei {n} {rules}.',
    '{month}: {n} {rules} liegen im Warnbereich; prüfe den Spielraum.',
    '{month}: Für {n} {rules} besteht eine Warnung; die Befunde zeigen mehr.',
    '{month}: {n} Regelwarnungen – ein guter Zeitpunkt, die Ursachen anzusehen.',
    '{month}: Die Prüfung zeigt Warnungen bei {n} {rules}.',
    '{month}: {n} {rules} im Warnbereich – behalte die Entwicklung im Blick.',
    '{month}: Warnstufe bei {n} {rules}; prüfe die konkreten Hinweise.',
    '{month}: {n} {rules} geben ein Warnsignal; die Details helfen beim Einordnen.',
    '{month}: {n} {rules} mit Warnung – der Finanz-Check meldet sich rechtzeitig.',
  ],
  'rule-ok': [
    '{month}: Der Finanz-Check bestätigt {n} erfüllte {rules}.',
    '{month}: {n} {rules} bewertet – die Prüfung zeigt keine Verletzung.',
    '{month}: Der Finanz-Check zeigt {n} erfüllte {rules} und keine Warnung.',
    '{month}: {n} {rules} geprüft – alle bewerteten Grenzen halten.',
    '{month}: Der Finanz-Check bleibt im grünen Bereich bei {n} bewerteten {rules}.',
    '{month}: {n} erfüllte {rules} – die bewerteten Grundlagen passen.',
    '{month}: Die Prüfung meldet keine Warnung oder Verletzung bei {n} {rules}.',
    '{month}: Die Auswertung enthält {n} bewertete {rules}; keine Warnung und keine Verletzung.',
    '{month}: Die Regelprüfung bestätigt {n} erfüllte {rules}.',
    '{month}: {n} bewertete {rules} erfüllt – der Finanz-Check hat wenig zu melden.',
  ],
  milestone: [
    '{month}: Dein erster aufgezeichneter Monat ohne Planüberschreitung.',
    '{month}: Zum ersten Mal seit Aufzeichnungsbeginn bleiben die Ausgaben im Plan.',
    '{month}: Erstmals kein Überschreiten des Plans – ein neuer Meilenstein.',
    '{month}: Der erste Monat im Plan ist erreicht.',
    '{month}: Dein Plan hält erstmals über einen vollständigen Monat.',
    '{month}: Ein erster vollständiger Monat ohne Planüberschreitung ist geschafft.',
    '{month}: Die Aufzeichnungen zeigen erstmals einen Monat im Plan.',
    '{month}: Erstmals reicht der Plan für den ganzen Monat.',
    '{month}: Der erste Monat ohne Planüberschreitung steht in der Zeitreihe.',
    '{month}: Zum ersten Mal ohne Planüberschreitung – die Tabelle setzt ein Häkchen.',
  ],
  'category-streak': [
    '{month}: {category} bleibt seit {n} Monaten im Plan.',
    '{month}: {n} Monate in Folge ohne Planüberschreitung bei {category}.',
    '{category}: Dein Plan hält den {n}. Monat hintereinander.',
    '{month}: Für {category} reichen die geplanten Beträge seit {n} Monaten.',
    '{month}: {category} liegt seit {n} Monaten auf oder unter dem Plan.',
    '{month}: Die Reihe für {category} wächst auf {n} Monate im Plan.',
    '{month}: {n} Monate bei {category} im Plan – eine beständige Reihe.',
    '{category}: Seit {n} Monaten passen Ausgaben und Plan zusammen.',
    '{month}: Auch {category} hält den Plan, zum {n}. Mal in Folge.',
    '{month}: {category} hält seit {n} Monaten den Plan; die Zeile bleibt ruhig.',
  ],
  equivalent: [
    '{month}: {label} {amount} entspricht {equivalent} {equivalentUnit} für {category}.',
    '{month}: {amount} beim Wert {label} – etwa {equivalent} {equivalentUnitNom} für {category}.',
    '{label}: {amount}, gemessen an {category} rund {equivalent} {equivalentUnitNom}.',
    '{month}: Dein Wert {label} deckt rechnerisch {equivalent} {equivalentUnitNom} für {category}.',
    '{month}: Für {category} gemessen sind {amount} beim Wert {label} rund {equivalent} {equivalentUnitNom}.',
    '{month}: {label} erreicht {amount} – das sind {equivalent} {equivalentUnitNom} für {category}.',
    '{month}: Der Betrag {amount} entspricht {equivalent} {equivalentUnit} für {category}.',
    '{month}: {label} entspricht deinen Kosten für {category} mal {equivalent}.',
    '{month}: {amount} beim Wert {label}, oder {equivalent} {equivalentUnitNom} für {category}.',
    '{month}: {equivalent} {equivalentUnitNom} für {category} – so lassen sich {amount} einordnen.',
  ],
  negative: [
    '{month}: {label} {amount} – das Minus verdient einen Blick auf die Ursachen.',
    '{month}: {label} steht bei {amount}; prüfe die größten Treiber.',
    '{month}: {amount} beim Wert {label} – ein Minus, das sich erklären lässt.',
    '{month}: {label} liegt mit {amount} unter null; die Details zeigen die Ursachen.',
    '{month}: Ein negativer Wert bei {label}: {amount}; beginne mit den Einzelwerten.',
    '{label}: {amount} – für {month} lohnt sich ein Blick auf die Entwicklung.',
    '{month}: {label} {amount} – eine ehrliche Bestandsaufnahme für den nächsten Schritt.',
    '{month}: Beim Wert {label} stehen {amount}; prüfe, was das Minus ausgelöst hat.',
    '{month}: {label} {amount} – prüfe die größten Treiber und den nächsten Schritt.',
    '{month}: {label} {amount} – die Zahl ist negativ, die Ursachen bleiben prüfbar.',
  ],
  summary: [
    '{month}: {label} {amount} – die Einzelwerte zeigen den Zusammenhang.',
    '{month}: Der ausgewiesene Wert für {label} beträgt {amount}.',
    '{month}: {label} steht bei {amount}; die Details ordnen den Wert ein.',
    '{label}: {amount} – das ist der Stand für {month}.',
    '{month}: Im Mittelpunkt steht {label} mit {amount}.',
    '{month}: {label} {amount}; für die Einordnung hilft der Verlauf.',
    '{month}: Die Auswertung zeigt {amount} beim Wert {label}.',
    '{month}: {label} erreicht {amount}; dahinter stehen die aufgeführten Einzelwerte.',
    '{month}: {amount} beim Wert {label} – eine Bestandsaufnahme des Zeitraums.',
    '{month}: {label} {amount} – die Tabelle liefert die Einzelheiten dazu.',
  ],
  unavailable: [
    '{month}: Für ein belastbares Fazit fehlen vergleichbare Werte.',
    '{month}: Noch keine belastbare Vergleichsbasis für diesen Report.',
    '{month}: Die vorhandenen Daten reichen noch nicht für ein Zahlenfazit.',
    '{month}: Ein Fazit braucht vollständige Werte; die Vergleichsbasis ist noch offen.',
    '{month}: Ohne vergleichbare Werte bleibt das Fazit offen.',
    '{month}: Die Vergleichsbasis ist unvollständig; prüfe die Hinweise im Report.',
    '{month}: Für die Einordnung fehlen noch belastbare Zahlen.',
    '{month}: Die Datenbasis trägt derzeit keinen belastbaren Vergleich.',
    '{month}: Noch kein Zahlenfazit – die Datenhinweise zeigen, was fehlt.',
    '{month}: Das Fazit bleibt offen, bis die benötigten Werte vorliegen.',
  ],
  neutral: [
    '{month}: Für eine besondere Entwicklung gibt es derzeit keinen belastbaren Hinweis.',
    '{month}: Die Einzelwerte geben den Überblick; ein besonderer Ausschlag ist nicht belegt.',
    '{month}: Der Report ordnet den Zeitraum ein, ohne einen besonderen Ausschlag zu behaupten.',
    '{month}: Für einen belastbaren Rekordvergleich reicht die vorhandene Zeitreihe nicht.',
    '{month}: Die Daten zeigen den Stand; für einen besonderen Vergleich fehlt noch die Grundlage.',
    '{month}: Die Einzelwerte helfen beim Einordnen dieses Zeitraums.',
    '{month}: Der Zeitraum lässt sich anhand der aufgeführten Werte einordnen.',
    '{month}: Eine ruhige Bestandsaufnahme – die Details zeigen den Zusammenhang.',
    '{month}: Die Auswertung liefert den Überblick für diesen Zeitraum.',
    '{month}: Die Tabelle hat die Einzelheiten; ein besonderer Vergleich ist noch nicht belegt.',
  ],
};
export const VERDICT_TEMPLATES: readonly VerdictTemplate[] = Object.entries(bank).flatMap(
  ([type, texts]) =>
    texts.map((text, i) => ({
      id: `${type}-${i + 1}`,
      type: type as VerdictFactType,
      tone:
        type === 'record-low' ||
        type === 'negative' ||
        type === 'rule-bad' ||
        type === 'rule-warn' ||
        type === 'market-down'
          ? 'warnend'
          : i === 9
            ? 'trocken-humorvoll'
            : i % 3 === 1
              ? 'anerkennend'
              : 'sachlich',
      text,
    })),
);
