import test from 'node:test';import assert from 'node:assert/strict';
import {strategyDebts,simulateDebtStrategy,gateExtraPayment,compareDebtStrategies} from '../debt-strategy.mjs';
import {renderDebtStrategy} from '../src/debt-strategy.js';
import {today} from '../model.mjs';
const loan=(id,balance,rate,min,fees=0)=>({id,accountId:id,name:id,balanceEURcents:balance,monthlyRate:rate,minimumEURcents:min,monthlyFeesEURcents:fees,dueDay:31,complete:true});
test('debt strategy view defaults asOf to today() in Europe/Vienna, not to the UTC date (E-01)',()=>{const live={accounts:[{id:'d',name:'bankA',balance:100000}],schedules:[],transactions:[],payees:[],categories:[]},workspace={settings:{salary:0,contribution:0,liquidity:{dailySpendEURcents:0}}};const html=renderDebtStrategy({live,workspace});assert.ok(html.includes('data-debt-strategy'));assert.match(today(),/^\d{4}-\d{2}-\d{2}$/);assert.ok(!html.includes('Offen'),'missing values use the shared EMPTY placeholder');assert.ok(html.includes('Simulation · keine Zahlungen'));});
const forecast=(extra={})=>({asOf:'2026-01-01',to:'2026-02-28',complete:true,minAvailable:80000,series:[{date:'2026-01-01',available:100000},{date:'2026-01-31',available:90000},{date:'2026-02-28',available:80000}],events:[],...extra});
test('avalanche and snowball conserve cents and roll freed minimums into common budget',()=>{
 const debts=[loan('high',100000,.01,10000),loan('small',20000,.001,5000)],options={startMonth:'2026-02',extraEURcents:10000},a=simulateDebtStrategy(debts,{...options,strategy:'avalanche'}),s=simulateDebtStrategy(debts,{...options,strategy:'snowball'});
 assert.equal(a.valid,true);assert.equal(s.valid,true);assert.ok(a.interestEURcents<s.interestEURcents);assert.equal(a.monthlyBudgetEURcents,25000);
 for(const result of [a,s]){assert.equal(result.totalPaidEURcents,result.startingDebtEURcents+result.interestEURcents+result.knownFeesEURcents);assert.equal(result.rows.at(-1).balanceEURcents,0);assert.ok(result.rows.slice(0,-1).every(r=>r.paymentEURcents===25000));assert.ok(result.rows.every(r=>r.paymentEURcents<=25000));}
 assert.equal(s.loans.find(d=>d.id==='small').paidOffMonth,'2026-03');assert.ok(s.loans.find(d=>d.id==='small').paidOffMonth<s.loans.find(d=>d.id==='high').paidOffMonth);
});
test('zero APR debt ends without invented interest or final overpayment',()=>{const r=simulateDebtStrategy([loan('a',10000,0,1000),loan('b',10000,0,1000)],{startMonth:'2026-02',extraEURcents:1000});assert.equal(r.months,7);assert.equal(r.totalPaidEURcents,20000);assert.equal(r.interestEURcents,0);assert.equal(r.rows.at(-1).paymentEURcents,2000);});
test('insufficient monthly payment stops rather than inventing a payoff date',()=>{const r=simulateDebtStrategy([loan('a',100000,.01,500)],{startMonth:'2026-02'});assert.equal(r.valid,false);assert.match(r.reason,/deckt Zinsen/);assert.deepEqual(r.insufficientIds,['a']);});
test('full-pay cards excluded, unknown balances and future-only terms stay missing',()=>{const live={accounts:[{id:'v',name:'Visa',balance:-10000},{id:'a',name:'Loan',balance:null},{id:'b',name:'Loan 2',balance:-50000}]},settings={debts:[{id:'da',accountId:'a',terms:[{effectiveFrom:'2026-01-01',nominalApr:5,paymentEURcents:10000}]},{id:'db',accountId:'b',terms:[{effectiveFrom:'2027-01-01',nominalApr:5,paymentEURcents:10000}]}]};const scope=strategyDebts(live,settings,'2026-09-23');assert.equal(scope.excluded[0].accountId,'v');assert.equal(scope.rows[0].balanceEURcents,null);assert.equal(scope.complete,false);assert.ok(scope.rows[1].missing.some(m=>m.includes('gültige')));});
test('effective APR converts to monthly rate instead of nominal division',()=>{const scope=strategyDebts({accounts:[{id:'a',balance:-10000}]},{debtProfiles:{a:{effectiveApr:12,minimumPaymentEURcents:1000}}},'2026-09-23');assert.ok(Math.abs(scope.rows[0].monthlyRate-(Math.pow(1.12,1/12)-1))<1e-12);});
test('liquidity gates recurring extra after buffer and reserves unlinked minimums once',()=>{const debts=[loan('a',100000,.01,10000)],gate=gateExtraPayment(debts,forecast(),40000);assert.equal(gate.allowedEURcents,30000);assert.equal(gate.uncoveredMinimums.length,2);const proven=gateExtraPayment(debts,forecast({events:[{date:'2026-01-31',counterpartyAccountId:'a',amountEURcents:-10000},{date:'2026-02-28',counterpartyAccountId:'a',amountEURcents:-10000}]}),40000);assert.equal(proven.allowedEURcents,40000);assert.equal(proven.uncoveredMinimums.length,0);});
test('unknown cash availability and existing shortfall never permit extra payment',()=>{assert.equal(gateExtraPayment([loan('a',10000,0,1000)],forecast({complete:false,minAvailable:null}),1000).allowedEURcents,0);const gate=gateExtraPayment([loan('a',10000,0,1000)],forecast({series:[{date:'2026-01-31',available:500}]}),0);assert.equal(gate.baseAffordable,false);assert.equal(gate.minimumShortfallEURcents,500);assert.match(gate.reason,/Schon der Basisplan/);});
test('unknown fees leave net advantage and fee break-even unknown, despite modeled interest',()=>{const live={accounts:[{id:'a',balance:-100000},{id:'b',balance:-20000}]},settings={debtProfiles:{a:{nominalApr:12,minimumPaymentEURcents:10000},b:{nominalApr:1,minimumPaymentEURcents:5000}}};const result=compareDebtStrategies(live,settings,forecast(),{asOf:'2026-01-01',requestedExtraEURcents:10000,avalancheFeeEURcents:0,snowballFeeEURcents:0});assert.equal(result.valid,true);assert.equal(result.netAdvantageEURcents,null);assert.equal(result.feeBreakEvenEURcents,null);assert.ok(Number.isSafeInteger(result.interestAdvantageEURcents));});
test('known fees make net advantage exact and strategy settings never mutate ledger',()=>{const live={accounts:[{id:'a',balance:-100000},{id:'b',balance:-20000}]},settings={debtProfiles:{a:{nominalApr:12,minimumPaymentEURcents:10000,monthlyFeesEURcents:100},b:{nominalApr:1,minimumPaymentEURcents:5000,monthlyFeesEURcents:0}}},before=structuredClone(live);const result=compareDebtStrategies(live,settings,forecast(),{asOf:'2026-01-01',requestedExtraEURcents:10000,avalancheFeeEURcents:500,snowballFeeEURcents:0});assert.equal(result.netAdvantageEURcents,result.snowball.totalFinancingCostEURcents-result.avalanche.totalFinancingCostEURcents-500);assert.deepEqual(live,before);});
test('native debt strategy UI keeps missing dataset visible and escapes loan names',()=>{const live={accounts:[{id:'d',name:'bankA',balance:100000},{id:'loan',name:'<script>x</script>',balance:null}],schedules:[],transactions:[],payees:[],categories:[]},workspace={settings:{salary:0,contribution:0,liquidity:{dailySpendEURcents:0}}};const html=renderDebtStrategy({live,workspace},{asOf:'2026-09-23'});assert.ok(html.includes('Aktueller belegter Kontosaldo'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('data-debt-strategy'));});
