-- P1f-3 (C3, C6, C7, C9, C12, C14): ledger model v2. The last migration that rebuilds tables;
-- from here on migrations are additive only (docs/ops.md section 11).
-- Generated by drizzle-kit, then edited by hand: copy statements list only columns the old tables
-- have, account type/on_budget are derived from the old role, links and targets move to their new
-- tables, standard rows and the version trigger come at the end. `migrateDatabase` switches
-- foreign keys off around the migrator and runs `foreign_key_check` afterwards.
CREATE TABLE `budget_month` (
	`month` text PRIMARY KEY NOT NULL,
	`held_cents` integer DEFAULT 0 NOT NULL,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	CONSTRAINT "budget_month_month_chk" CHECK("budget_month"."month" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]'),
	CONSTRAINT "budget_month_held_chk" CHECK("budget_month"."held_cents" >= 0)
);
--> statement-breakpoint
CREATE TABLE `category_target` (
	`id` text PRIMARY KEY NOT NULL,
	`category_id` text NOT NULL,
	`kind` text NOT NULL,
	`amount_cents` integer NOT NULL,
	`every_months` integer DEFAULT 1 NOT NULL,
	`target_date` text,
	`valid_from` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "category_target_kind_chk" CHECK("category_target"."kind" IN ('monthly', 'by_date', 'keep_balance')),
	CONSTRAINT "category_target_amount_chk" CHECK("category_target"."amount_cents" >= 0),
	CONSTRAINT "category_target_every_chk" CHECK("category_target"."every_months" BETWEEN 1 AND 120),
	CONSTRAINT "category_target_date_chk" CHECK(("category_target"."kind" = 'by_date') = ("category_target"."target_date" IS NOT NULL)),
	CONSTRAINT "category_target_target_date_chk" CHECK("category_target"."target_date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "category_target_valid_from_chk" CHECK("category_target"."valid_from" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]')
);
--> statement-breakpoint
CREATE UNIQUE INDEX `category_target_uq` ON `category_target` (`category_id`,`valid_from`);--> statement-breakpoint
CREATE TABLE `income_type` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text
);
--> statement-breakpoint
CREATE TABLE `import_mapping` (
	`id` text PRIMARY KEY NOT NULL,
	`import_run_id` text NOT NULL,
	`version` integer NOT NULL,
	`schema_version` integer DEFAULT 1 NOT NULL,
	`mapping_json` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`import_run_id`) REFERENCES `import_run`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "import_mapping_version_chk" CHECK("import_mapping"."version" >= 1)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `import_mapping_uq` ON `import_mapping` (`import_run_id`,`version`);--> statement-breakpoint
CREATE TABLE `import_run` (
	`id` text PRIMARY KEY NOT NULL,
	`source` text NOT NULL,
	`status` text DEFAULT 'staged' NOT NULL,
	`file_name` text,
	`file_sha256` text,
	`mapping_version` integer,
	`rules_from` text,
	`summary_json` text,
	`started_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`finished_at` text,
	`committed_at` text,
	`reverted_at` text,
	CONSTRAINT "import_run_source_chk" CHECK("import_run"."source" IN ('ynab', 'csv', 'bank', 'portfolio_performance', 'other')),
	CONSTRAINT "import_run_status_chk" CHECK("import_run"."status" IN ('staged', 'dry_run', 'committed', 'reverted', 'failed')),
	CONSTRAINT "import_run_rules_from_chk" CHECK("import_run"."rules_from" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]')
);
--> statement-breakpoint
CREATE TABLE `ynab_plan_row` (
	`id` text PRIMARY KEY NOT NULL,
	`import_run_id` text NOT NULL,
	`row_no` integer NOT NULL,
	`month` text NOT NULL,
	`category_group_category` text DEFAULT '' NOT NULL,
	`category_group` text DEFAULT '' NOT NULL,
	`category` text DEFAULT '' NOT NULL,
	`assigned` text NOT NULL,
	`activity` text NOT NULL,
	`available` text NOT NULL,
	FOREIGN KEY (`import_run_id`) REFERENCES `import_run`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ynab_plan_row_uq` ON `ynab_plan_row` (`import_run_id`,`row_no`);--> statement-breakpoint
CREATE INDEX `ynab_plan_row_category_idx` ON `ynab_plan_row` (`import_run_id`,`category_group`,`category`);--> statement-breakpoint
CREATE TABLE `ynab_register_row` (
	`id` text PRIMARY KEY NOT NULL,
	`import_run_id` text NOT NULL,
	`row_no` integer NOT NULL,
	`account` text NOT NULL,
	`flag` text DEFAULT '' NOT NULL,
	`date` text NOT NULL,
	`payee` text DEFAULT '' NOT NULL,
	`category_group_category` text DEFAULT '' NOT NULL,
	`category_group` text DEFAULT '' NOT NULL,
	`category` text DEFAULT '' NOT NULL,
	`memo` text DEFAULT '' NOT NULL,
	`outflow` text NOT NULL,
	`inflow` text NOT NULL,
	`cleared` text NOT NULL,
	FOREIGN KEY (`import_run_id`) REFERENCES `import_run`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ynab_register_row_uq` ON `ynab_register_row` (`import_run_id`,`row_no`);--> statement-breakpoint
CREATE TABLE `account_reconciliation` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`date` text NOT NULL,
	`statement_balance_cents` integer NOT NULL,
	`cleared_balance_cents` integer NOT NULL,
	`adjustment_booking_id` text,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`adjustment_booking_id`) REFERENCES `booking`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "reconciliation_date_chk" CHECK("account_reconciliation"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
CREATE INDEX `reconciliation_account_date_idx` ON `account_reconciliation` (`account_id`,`date`);--> statement-breakpoint
CREATE TABLE `receipt_split` (
	`receipt_id` text NOT NULL,
	`split_id` text NOT NULL,
	PRIMARY KEY(`receipt_id`, `split_id`),
	FOREIGN KEY (`receipt_id`) REFERENCES `receipt`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`split_id`) REFERENCES `booking_split`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `receipt_split_split_idx` ON `receipt_split` (`split_id`);--> statement-breakpoint
INSERT OR IGNORE INTO `receipt_split`("receipt_id", "split_id") SELECT r."id", s."id" FROM `receipt` r JOIN `booking_split` s ON s."booking_id" = r."booking_id";--> statement-breakpoint
INSERT OR IGNORE INTO `receipt_split`("receipt_id", "split_id") SELECT b."receipt_id", s."id" FROM `booking` b JOIN `booking_split` s ON s."booking_id" = b."id" WHERE b."receipt_id" IS NOT NULL;--> statement-breakpoint
CREATE TABLE `expected_occurrence` (
	`id` text PRIMARY KEY NOT NULL,
	`expected_payment_id` text NOT NULL,
	`due_date` text NOT NULL,
	`expected_amount_cents` integer NOT NULL,
	`contact_share_cents` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'expected' NOT NULL,
	`booking_id` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`expected_payment_id`) REFERENCES `expected_payment`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`booking_id`) REFERENCES `booking`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "occurrence_status_chk" CHECK("expected_occurrence"."status" IN ('expected', 'received', 'deviating', 'missed')),
	CONSTRAINT "occurrence_due_date_chk" CHECK("expected_occurrence"."due_date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "occurrence_booking_chk" CHECK(("expected_occurrence"."status" IN ('received', 'deviating')) = ("expected_occurrence"."booking_id" IS NOT NULL))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `occurrence_uq` ON `expected_occurrence` (`expected_payment_id`,`due_date`);--> statement-breakpoint
CREATE INDEX `occurrence_booking_idx` ON `expected_occurrence` (`booking_id`);--> statement-breakpoint
CREATE TABLE `asset_class_target` (
	`id` text PRIMARY KEY NOT NULL,
	`asset_class_id` text NOT NULL,
	`valid_from` text NOT NULL,
	`target_share_bp` integer NOT NULL,
	`band_bp` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`asset_class_id`) REFERENCES `asset_class`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "asset_class_target_valid_from_chk" CHECK("asset_class_target"."valid_from" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "asset_class_target_share_chk" CHECK("asset_class_target"."target_share_bp" BETWEEN 0 AND 10000),
	CONSTRAINT "asset_class_target_band_chk" CHECK("asset_class_target"."band_bp" BETWEEN 0 AND 10000)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `asset_class_target_uq` ON `asset_class_target` (`asset_class_id`,`valid_from`);--> statement-breakpoint
CREATE TABLE `price_audit` (
	`id` text PRIMARY KEY NOT NULL,
	`security_id` text NOT NULL,
	`date` text NOT NULL,
	`old_price_micro` integer,
	`new_price_micro` integer NOT NULL,
	`old_source` text,
	`new_source` text NOT NULL,
	`ts` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`security_id`) REFERENCES `security`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `price_audit_security_idx` ON `price_audit` (`security_id`,`date`);--> statement-breakpoint
CREATE TABLE `valuation` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`date` text NOT NULL,
	`value_cents` integer NOT NULL,
	`source` text DEFAULT 'manual' NOT NULL,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "valuation_source_chk" CHECK("valuation"."source" IN ('manual', 'import', 'statement')),
	CONSTRAINT "valuation_date_chk" CHECK("valuation"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
CREATE UNIQUE INDEX `valuation_uq` ON `valuation` (`account_id`,`date`);--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_booking` (
	`id` text PRIMARY KEY NOT NULL,
	`account_id` text NOT NULL,
	`date` text NOT NULL,
	`amount_cents` integer NOT NULL,
	`payee_id` text,
	`memo` text,
	`status` text DEFAULT 'confirmed' NOT NULL,
	`flag` text,
	`transfer_id` text,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`original_amount_cents` integer,
	`original_currency` text,
	`fx_rate_micro` integer,
	`fx_fee_cents` integer,
	`project_id` text,
	`source` text DEFAULT 'manual' NOT NULL,
	`import_key` text,
	`import_run_id` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`payee_id`) REFERENCES `payee`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`transfer_id`) REFERENCES `transfer`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`import_run_id`) REFERENCES `import_run`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "booking_status_chk" CHECK("__new_booking"."status" IN ('pending', 'confirmed', 'reconciled')),
	CONSTRAINT "booking_source_chk" CHECK("__new_booking"."source" IN ('manual', 'bank', 'import', 'migration', 'system')),
	CONSTRAINT "booking_flag_chk" CHECK("__new_booking"."flag" IN ('red', 'orange', 'yellow', 'green', 'blue', 'purple')),
	CONSTRAINT "booking_date_chk" CHECK("__new_booking"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "booking_fx_all_or_none_chk" CHECK(("__new_booking"."original_amount_cents" IS NULL) = ("__new_booking"."original_currency" IS NULL)
        AND ("__new_booking"."original_currency" IS NULL) = ("__new_booking"."fx_rate_micro" IS NULL)
        AND ("__new_booking"."fx_rate_micro" IS NULL) = ("__new_booking"."fx_fee_cents" IS NULL)),
	CONSTRAINT "booking_fx_values_chk" CHECK("__new_booking"."original_amount_cents" IS NULL OR (
        "__new_booking"."fx_rate_micro" > 0
        AND "__new_booking"."original_currency" <> "__new_booking"."currency"
        AND ("__new_booking"."original_amount_cents" > 0) = ("__new_booking"."amount_cents" > 0)
        AND ("__new_booking"."original_amount_cents" < 0) = ("__new_booking"."amount_cents" < 0)))
);
--> statement-breakpoint
INSERT INTO `__new_booking`("id", "account_id", "date", "amount_cents", "payee_id", "memo", "status", "transfer_id", "currency", "original_amount_cents", "original_currency", "fx_rate_micro", "fx_fee_cents", "project_id", "source", "import_key", "created_at", "updated_at", "deleted_at") SELECT "id", "account_id", "date", "amount_cents", "payee_id", "memo", "status", "transfer_id", "currency", "original_amount_cents", "original_currency", "fx_rate_micro", "fx_fee_cents", "project_id", "source", "import_key", "created_at", "updated_at", "deleted_at" FROM `booking`;--> statement-breakpoint
DROP TABLE `booking`;--> statement-breakpoint
ALTER TABLE `__new_booking` RENAME TO `booking`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `booking_account_date_idx` ON `booking` (`account_id`,`date`);--> statement-breakpoint
CREATE INDEX `booking_date_idx` ON `booking` (`date`);--> statement-breakpoint
CREATE INDEX `booking_transfer_idx` ON `booking` (`transfer_id`);--> statement-breakpoint
CREATE INDEX `booking_payee_idx` ON `booking` (`payee_id`);--> statement-breakpoint
CREATE INDEX `booking_project_idx` ON `booking` (`project_id`);--> statement-breakpoint
CREATE INDEX `booking_import_run_idx` ON `booking` (`import_run_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `booking_import_key_uq` ON `booking` (`account_id`,`import_key`) WHERE "booking"."import_key" IS NOT NULL;--> statement-breakpoint
CREATE TABLE `__new_category` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`group_id` text NOT NULL,
	`class` text,
	`kind` text DEFAULT 'variable' NOT NULL,
	`stage` integer,
	`card_account_id` text,
	`rollover_overspending` integer DEFAULT false NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`hidden_at` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`group_id`) REFERENCES `category_group`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`card_account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "category_class_chk" CHECK("__new_category"."class" IN ('need', 'want', 'future')),
	CONSTRAINT "category_kind_chk" CHECK("__new_category"."kind" IN ('fixed', 'periodic', 'variable', 'project', 'saving', 'invest', 'debt', 'advance', 'card_payment', 'income')),
	CONSTRAINT "category_class_required_chk" CHECK(("__new_category"."class" IS NULL) = ("__new_category"."kind" IN ('income', 'card_payment', 'advance'))),
	CONSTRAINT "category_stage_chk" CHECK("__new_category"."stage" BETWEEN 1 AND 9),
	CONSTRAINT "category_card_account_chk" CHECK(("__new_category"."card_account_id" IS NOT NULL) = ("__new_category"."kind" = 'card_payment'))
);
--> statement-breakpoint
INSERT INTO `__new_category`("id", "name", "group_id", "class", "kind", "stage", "sort_order", "hidden_at", "created_at", "updated_at", "deleted_at") SELECT "id", "name", "group_id", "class", "kind", "stage", "sort_order", "hidden_at", "created_at", "updated_at", "deleted_at" FROM `category`;--> statement-breakpoint
DROP TABLE `category`;--> statement-breakpoint
ALTER TABLE `__new_category` RENAME TO `category`;--> statement-breakpoint
CREATE INDEX `category_group_idx` ON `category` (`group_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `category_card_account_uq` ON `category` (`card_account_id`) WHERE "category"."card_account_id" IS NOT NULL;--> statement-breakpoint
CREATE TABLE `__new_security` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`kind` text NOT NULL,
	`symbol` text,
	`isin` text,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`ter_bp` integer DEFAULT 0 NOT NULL,
	`asset_class_id` text,
	`institution_id` text,
	`regions_json` text,
	`benchmark` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`asset_class_id`) REFERENCES `asset_class`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`institution_id`) REFERENCES `institution`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "security_kind_chk" CHECK("__new_security"."kind" IN ('etf', 'stock', 'fund', 'bond', 'crypto', 'p2p', 'commodity', 'other'))
);
--> statement-breakpoint
INSERT INTO `__new_security`("id", "name", "kind", "symbol", "isin", "currency", "ter_bp", "asset_class_id", "institution_id", "regions_json", "benchmark", "created_at", "updated_at", "deleted_at") SELECT "id", "name", "kind", "symbol", "isin", "currency", "ter_bp", "asset_class_id", "institution_id", "regions_json", "benchmark", "created_at", "updated_at", "deleted_at" FROM `security`;--> statement-breakpoint
DROP TABLE `security`;--> statement-breakpoint
ALTER TABLE `__new_security` RENAME TO `security`;--> statement-breakpoint
CREATE TABLE `__new_trade` (
	`id` text PRIMARY KEY NOT NULL,
	`security_id` text NOT NULL,
	`account_id` text NOT NULL,
	`date` text NOT NULL,
	`kind` text NOT NULL,
	`units_e8` integer DEFAULT 0 NOT NULL,
	`amount_cents` integer NOT NULL,
	`fee_cents` integer DEFAULT 0 NOT NULL,
	`tax_cents` integer DEFAULT 0 NOT NULL,
	`booking_id` text,
	`import_key` text,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`security_id`) REFERENCES `security`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`booking_id`) REFERENCES `booking`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "trade_kind_chk" CHECK("__new_trade"."kind" IN ('buy', 'sell', 'delivery_in', 'delivery_out', 'split', 'dividend', 'interest', 'fee', 'tax')),
	CONSTRAINT "trade_units_chk" CHECK(CASE
        WHEN "__new_trade"."kind" IN ('buy', 'delivery_in') THEN "__new_trade"."units_e8" > 0
        WHEN "__new_trade"."kind" IN ('sell', 'delivery_out') THEN "__new_trade"."units_e8" < 0
        WHEN "__new_trade"."kind" = 'split' THEN "__new_trade"."units_e8" <> 0
        ELSE "__new_trade"."units_e8" = 0 END),
	CONSTRAINT "trade_amounts_chk" CHECK("__new_trade"."amount_cents" >= 0 AND "__new_trade"."fee_cents" >= 0 AND "__new_trade"."tax_cents" >= 0),
	CONSTRAINT "trade_date_chk" CHECK("__new_trade"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_trade`("id", "security_id", "account_id", "date", "kind", "units_e8", "amount_cents", "fee_cents", "booking_id", "import_key", "note", "created_at", "updated_at", "deleted_at") SELECT "id", "security_id", "account_id", "date", "kind", "units_e8", "amount_cents", "fee_cents", "booking_id", "import_key", "note", "created_at", "updated_at", "deleted_at" FROM `trade`;--> statement-breakpoint
DROP TABLE `trade`;--> statement-breakpoint
ALTER TABLE `__new_trade` RENAME TO `trade`;--> statement-breakpoint
CREATE INDEX `trade_security_date_idx` ON `trade` (`security_id`,`date`);--> statement-breakpoint
CREATE INDEX `trade_account_date_idx` ON `trade` (`account_id`,`date`);--> statement-breakpoint
CREATE UNIQUE INDEX `trade_import_key_uq` ON `trade` (`account_id`,`import_key`);--> statement-breakpoint
CREATE TABLE `__new_inbox_item` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`title` text NOT NULL,
	`detail` text,
	`ref_type` text,
	`ref_id` text,
	`urgent` integer DEFAULT false NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`resolved_at` text,
	`resolution` text,
	CONSTRAINT "inbox_kind_chk" CHECK("__new_inbox_item"."kind" IN ('uncategorized', 'revision', 'import', 'stale_value', 'consent', 'overspent', 'expected_payment', 'receivable', 'reconciliation', 'backup', 'other'))
);
--> statement-breakpoint
INSERT INTO `__new_inbox_item`("id", "kind", "title", "detail", "ref_type", "ref_id", "urgent", "created_at", "resolved_at", "resolution") SELECT "id", "kind", "title", "detail", "ref_type", "ref_id", "urgent", "created_at", "resolved_at", "resolution" FROM `inbox_item`;--> statement-breakpoint
DROP TABLE `inbox_item`;--> statement-breakpoint
ALTER TABLE `__new_inbox_item` RENAME TO `inbox_item`;--> statement-breakpoint
CREATE INDEX `inbox_open_idx` ON `inbox_item` (`resolved_at`);--> statement-breakpoint
CREATE TABLE `__new_account` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`role` text NOT NULL,
	`on_budget` integer NOT NULL,
	`institution_id` text,
	`contact_id` text,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`opening_balance_cents` integer DEFAULT 0 NOT NULL,
	`opening_date` text NOT NULL,
	`credit_limit_cents` integer,
	`overdraft_limit_cents` integer,
	`interest_rate_bp` integer,
	`term_end` text,
	`monthly_fee_cents` integer,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`closed_at` text,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`institution_id`) REFERENCES `institution`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "account_type_chk" CHECK("__new_account"."type" IN ('checking', 'cash', 'savings', 'credit_card', 'loan', 'brokerage', 'crypto', 'p2p', 'receivable', 'other_asset', 'other_liability')),
	CONSTRAINT "account_role_chk" CHECK("__new_account"."role" IN ('budget', 'reserve', 'investment', 'debt', 'receivable')),
	CONSTRAINT "account_on_budget_chk" CHECK("__new_account"."on_budget" = 0 OR "__new_account"."type" NOT IN ('loan', 'brokerage', 'crypto', 'p2p', 'receivable')),
	CONSTRAINT "account_opening_date_chk" CHECK("__new_account"."opening_date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "account_term_end_chk" CHECK("__new_account"."term_end" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_account`("id", "name", "role", "institution_id", "contact_id", "currency", "opening_balance_cents", "opening_date", "credit_limit_cents", "overdraft_limit_cents", "interest_rate_bp", "term_end", "monthly_fee_cents", "sort_order", "closed_at", "note", "created_at", "updated_at", "deleted_at", "type", "on_budget") SELECT "id", "name", "role", "institution_id", "contact_id", "currency", "opening_balance_cents", "opening_date", "credit_limit_cents", "overdraft_limit_cents", "interest_rate_bp", "term_end", "monthly_fee_cents", "sort_order", "closed_at", "note", "created_at", "updated_at", "deleted_at", CASE "role" WHEN 'budget' THEN 'checking' WHEN 'reserve' THEN 'savings' WHEN 'investment' THEN 'brokerage' WHEN 'debt' THEN 'loan' ELSE 'receivable' END, "role" IN ('budget', 'reserve') FROM `account`;--> statement-breakpoint
DROP TABLE `account`;--> statement-breakpoint
ALTER TABLE `__new_account` RENAME TO `account`;--> statement-breakpoint
CREATE INDEX `account_role_idx` ON `account` (`role`);--> statement-breakpoint
CREATE TABLE `__new_expected_payment` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`kind` text DEFAULT 'outflow' NOT NULL,
	`account_id` text,
	`payee_id` text,
	`contact_id` text,
	`category_id` text,
	`income_type_id` text,
	`contact_share_bp` integer DEFAULT 0 NOT NULL,
	`amount_tolerance_cents` integer DEFAULT 0 NOT NULL,
	`date_window_days` integer DEFAULT 3 NOT NULL,
	`rhythm` text DEFAULT 'monthly' NOT NULL,
	`due_day` integer DEFAULT 1 NOT NULL,
	`due_month` integer,
	`start_date` text,
	`end_date` text,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`payee_id`) REFERENCES `payee`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`income_type_id`) REFERENCES `income_type`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "expected_kind_chk" CHECK("__new_expected_payment"."kind" IN ('outflow', 'inflow')),
	CONSTRAINT "expected_rhythm_chk" CHECK("__new_expected_payment"."rhythm" IN ('monthly', 'quarterly', 'semiannual', 'yearly')),
	CONSTRAINT "expected_due_day_chk" CHECK("__new_expected_payment"."due_day" BETWEEN 1 AND 31),
	CONSTRAINT "expected_due_month_chk" CHECK("__new_expected_payment"."due_month" BETWEEN 1 AND 12),
	CONSTRAINT "expected_share_chk" CHECK("__new_expected_payment"."contact_share_bp" BETWEEN 0 AND 10000),
	CONSTRAINT "expected_share_contact_chk" CHECK("__new_expected_payment"."contact_share_bp" = 0 OR "__new_expected_payment"."contact_id" IS NOT NULL),
	CONSTRAINT "expected_category_or_income_chk" CHECK("__new_expected_payment"."category_id" IS NULL OR "__new_expected_payment"."income_type_id" IS NULL),
	CONSTRAINT "expected_tolerance_chk" CHECK("__new_expected_payment"."amount_tolerance_cents" >= 0),
	CONSTRAINT "expected_window_chk" CHECK("__new_expected_payment"."date_window_days" BETWEEN 0 AND 31),
	CONSTRAINT "expected_start_chk" CHECK("__new_expected_payment"."start_date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "expected_end_chk" CHECK("__new_expected_payment"."end_date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_expected_payment`("id", "name", "kind", "account_id", "payee_id", "category_id", "rhythm", "due_day", "due_month", "start_date", "end_date", "note", "created_at", "updated_at", "deleted_at") SELECT "id", "name", "kind", "account_id", "payee_id", "category_id", "rhythm", "due_day", "due_month", "start_date", "end_date", "note", "created_at", "updated_at", "deleted_at" FROM `expected_payment`;--> statement-breakpoint
DROP TABLE `expected_payment`;--> statement-breakpoint
ALTER TABLE `__new_expected_payment` RENAME TO `expected_payment`;--> statement-breakpoint
CREATE TABLE `__new_expected_payment_version` (
	`id` text PRIMARY KEY NOT NULL,
	`expected_payment_id` text NOT NULL,
	`valid_from` text NOT NULL,
	`amount_cents` integer NOT NULL,
	`amount_max_cents` integer,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`original_amount_cents` integer,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`expected_payment_id`) REFERENCES `expected_payment`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "expected_version_valid_from_chk" CHECK("__new_expected_payment_version"."valid_from" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "expected_version_range_chk" CHECK("__new_expected_payment_version"."amount_max_cents" IS NULL OR "__new_expected_payment_version"."amount_max_cents" >= "__new_expected_payment_version"."amount_cents")
);
--> statement-breakpoint
INSERT INTO `__new_expected_payment_version`("id", "expected_payment_id", "valid_from", "amount_cents", "currency", "original_amount_cents", "note", "created_at", "updated_at", "deleted_at") SELECT "id", "expected_payment_id", "valid_from", "amount_cents", "currency", "original_amount_cents", "note", "created_at", "updated_at", "deleted_at" FROM `expected_payment_version`;--> statement-breakpoint
DROP TABLE `expected_payment_version`;--> statement-breakpoint
ALTER TABLE `__new_expected_payment_version` RENAME TO `expected_payment_version`;--> statement-breakpoint
CREATE UNIQUE INDEX `expected_version_uq` ON `expected_payment_version` (`expected_payment_id`,`valid_from`);--> statement-breakpoint
CREATE TABLE `__new_payee` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`contact_id` text,
	`default_category_id` text,
	`system_kind` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`default_category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "payee_system_kind_chk" CHECK("__new_payee"."system_kind" IN ('opening_balance', 'reconciliation_adjustment', 'manual_adjustment'))
);
--> statement-breakpoint
INSERT INTO `__new_payee`("id", "name", "contact_id", "default_category_id", "created_at", "updated_at", "deleted_at") SELECT "id", "name", "contact_id", "default_category_id", "created_at", "updated_at", "deleted_at" FROM `payee`;--> statement-breakpoint
DROP TABLE `payee`;--> statement-breakpoint
ALTER TABLE `__new_payee` RENAME TO `payee`;--> statement-breakpoint
CREATE UNIQUE INDEX `payee_system_kind_uq` ON `payee` (`system_kind`) WHERE "payee"."system_kind" IS NOT NULL;--> statement-breakpoint
CREATE TABLE `__new_booking_split` (
	`id` text PRIMARY KEY NOT NULL,
	`booking_id` text NOT NULL,
	`category_id` text,
	`amount_cents` integer NOT NULL,
	`memo` text,
	`contact_id` text,
	`income_type_id` text,
	`transfer_id` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`booking_id`) REFERENCES `booking`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`income_type_id`) REFERENCES `income_type`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`transfer_id`) REFERENCES `transfer`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "split_contact_or_transfer_chk" CHECK("__new_booking_split"."contact_id" IS NULL OR "__new_booking_split"."transfer_id" IS NULL),
	CONSTRAINT "split_income_type_chk" CHECK("__new_booking_split"."income_type_id" IS NULL OR ("__new_booking_split"."contact_id" IS NULL AND "__new_booking_split"."transfer_id" IS NULL))
);
--> statement-breakpoint
INSERT INTO `__new_booking_split`("id", "booking_id", "category_id", "amount_cents", "memo", "contact_id", "sort_order") SELECT "id", "booking_id", "category_id", "amount_cents", "memo", "contact_id", "sort_order" FROM `booking_split`;--> statement-breakpoint
DROP TABLE `booking_split`;--> statement-breakpoint
ALTER TABLE `__new_booking_split` RENAME TO `booking_split`;--> statement-breakpoint
CREATE INDEX `split_booking_idx` ON `booking_split` (`booking_id`);--> statement-breakpoint
CREATE INDEX `split_category_idx` ON `booking_split` (`category_id`);--> statement-breakpoint
CREATE INDEX `split_contact_idx` ON `booking_split` (`contact_id`);--> statement-breakpoint
CREATE INDEX `split_transfer_idx` ON `booking_split` (`transfer_id`);--> statement-breakpoint
CREATE TABLE `__new_payslip` (
	`id` text PRIMARY KEY NOT NULL,
	`month` text NOT NULL,
	`kind` text DEFAULT 'regular' NOT NULL,
	`gross_cents` integer NOT NULL,
	`net_cents` integer NOT NULL,
	`employer_contact_id` text,
	`booking_id` text,
	`receipt_id` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`employer_contact_id`) REFERENCES `contact`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`booking_id`) REFERENCES `booking`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`receipt_id`) REFERENCES `receipt`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "payslip_kind_chk" CHECK("__new_payslip"."kind" IN ('regular', 'special')),
	CONSTRAINT "payslip_month_chk" CHECK("__new_payslip"."month" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_payslip`("id", "month", "kind", "gross_cents", "net_cents", "receipt_id", "created_at", "updated_at", "deleted_at") SELECT "id", "month", "kind", "gross_cents", "net_cents", "receipt_id", "created_at", "updated_at", "deleted_at" FROM `payslip`;--> statement-breakpoint
DROP TABLE `payslip`;--> statement-breakpoint
ALTER TABLE `__new_payslip` RENAME TO `payslip`;--> statement-breakpoint
CREATE INDEX `payslip_booking_idx` ON `payslip` (`booking_id`);--> statement-breakpoint
CREATE TABLE `__new_envelope_month` (
	`category_id` text NOT NULL,
	`month` text NOT NULL,
	`assigned_cents` integer DEFAULT 0 NOT NULL,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	PRIMARY KEY(`category_id`, `month`),
	FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "envelope_month_month_chk" CHECK("__new_envelope_month"."month" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_envelope_month`("category_id", "month", "assigned_cents", "note", "created_at", "updated_at", "deleted_at") SELECT "category_id", "month", "assigned_cents", "note", "created_at", "updated_at", "deleted_at" FROM `envelope_month`;--> statement-breakpoint
DROP TABLE `envelope_month`;--> statement-breakpoint
ALTER TABLE `__new_envelope_month` RENAME TO `envelope_month`;--> statement-breakpoint
CREATE TABLE `__new_planned_event` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`date` text NOT NULL,
	`amount_cents` integer NOT NULL,
	`account_id` text,
	`category_id` text,
	`enabled` integer DEFAULT true NOT NULL,
	`note` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "planned_event_date_chk" CHECK("__new_planned_event"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_planned_event`("id", "name", "date", "amount_cents", "account_id", "category_id", "enabled", "note", "created_at", "updated_at", "deleted_at") SELECT "id", "name", "date", "amount_cents", "account_id", "category_id", "enabled", "note", "created_at", "updated_at", "deleted_at" FROM `planned_event`;--> statement-breakpoint
DROP TABLE `planned_event`;--> statement-breakpoint
ALTER TABLE `__new_planned_event` RENAME TO `planned_event`;--> statement-breakpoint
CREATE TABLE `__new_fx_rate` (
	`date` text NOT NULL,
	`currency` text NOT NULL,
	`rate_micro` integer NOT NULL,
	`source` text DEFAULT 'ecb' NOT NULL,
	PRIMARY KEY(`date`, `currency`),
	CONSTRAINT "fx_rate_date_chk" CHECK("__new_fx_rate"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "fx_rate_positive_chk" CHECK("__new_fx_rate"."rate_micro" > 0)
);
--> statement-breakpoint
INSERT INTO `__new_fx_rate`("date", "currency", "rate_micro", "source") SELECT "date", "currency", "rate_micro", "source" FROM `fx_rate`;--> statement-breakpoint
DROP TABLE `fx_rate`;--> statement-breakpoint
ALTER TABLE `__new_fx_rate` RENAME TO `fx_rate`;--> statement-breakpoint
CREATE TABLE `__new_holding` (
	`id` text PRIMARY KEY NOT NULL,
	`security_id` text NOT NULL,
	`account_id` text NOT NULL,
	`as_of` text NOT NULL,
	`units_e8` integer NOT NULL,
	`cost_basis_cents` integer,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	FOREIGN KEY (`security_id`) REFERENCES `security`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`account_id`) REFERENCES `account`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "holding_as_of_chk" CHECK("__new_holding"."as_of" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]')
);
--> statement-breakpoint
INSERT INTO `__new_holding`("id", "security_id", "account_id", "as_of", "units_e8", "cost_basis_cents", "created_at", "updated_at", "deleted_at") SELECT "id", "security_id", "account_id", "as_of", "units_e8", "cost_basis_cents", "created_at", "updated_at", "deleted_at" FROM `holding`;--> statement-breakpoint
DROP TABLE `holding`;--> statement-breakpoint
ALTER TABLE `__new_holding` RENAME TO `holding`;--> statement-breakpoint
CREATE UNIQUE INDEX `holding_uq` ON `holding` (`security_id`,`account_id`,`as_of`);--> statement-breakpoint
CREATE TABLE `__new_price` (
	`security_id` text NOT NULL,
	`date` text NOT NULL,
	`price_micro` integer NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`source` text NOT NULL,
	PRIMARY KEY(`security_id`, `date`),
	FOREIGN KEY (`security_id`) REFERENCES `security`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "price_source_chk" CHECK("__new_price"."source" IN ('yfinance', 'ariva', 'manual', 'import')),
	CONSTRAINT "price_date_chk" CHECK("__new_price"."date" GLOB '[0-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]'),
	CONSTRAINT "price_positive_chk" CHECK("__new_price"."price_micro" > 0)
);
--> statement-breakpoint
INSERT INTO `__new_price`("security_id", "date", "price_micro", "currency", "source") SELECT "security_id", "date", "price_micro", "currency", "source" FROM `price`;--> statement-breakpoint
DROP TABLE `price`;--> statement-breakpoint
ALTER TABLE `__new_price` RENAME TO `price`;--> statement-breakpoint
CREATE TABLE `__new_rule` (
	`id` text PRIMARY KEY NOT NULL,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`stage` integer,
	`goal` text,
	`params_json` text,
	`action` text,
	`enabled` integer DEFAULT true NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	CONSTRAINT "rule_stage_chk" CHECK("__new_rule"."stage" BETWEEN 1 AND 3)
);
--> statement-breakpoint
INSERT INTO `__new_rule`("id", "code", "name", "stage", "goal", "params_json", "action", "enabled", "created_at", "updated_at", "deleted_at") SELECT "id", "code", "name", "stage", "goal", "params_json", "action", "enabled", "created_at", "updated_at", "deleted_at" FROM `rule`;--> statement-breakpoint
DROP TABLE `rule`;--> statement-breakpoint
ALTER TABLE `__new_rule` RENAME TO `rule`;--> statement-breakpoint
CREATE UNIQUE INDEX `rule_code_unique` ON `rule` (`code`);--> statement-breakpoint
ALTER TABLE `receipt` DROP COLUMN `booking_id`;--> statement-breakpoint
INSERT INTO `asset_class_target`("id", "asset_class_id", "valid_from", "target_share_bp", "band_bp") SELECT 'act-' || "id", "id", '2023-10-01', "target_share_bp", 0 FROM `asset_class` WHERE "target_share_bp" IS NOT NULL;--> statement-breakpoint
ALTER TABLE `asset_class` DROP COLUMN `target_share_bp`;--> statement-breakpoint
INSERT INTO `income_type`("id", "name", "sort_order") VALUES
  ('income-salary', 'Gehalt', 1),
  ('income-special', 'Sonderzahlung', 2),
  ('income-contribution', 'Beiträge von Kontakten', 3),
  ('income-side', 'Nebeneinkünfte', 4),
  ('income-capital', 'Kapitalerträge', 5),
  ('income-refund', 'Erstattungen', 6),
  ('income-gift', 'Geschenke', 7),
  ('income-other', 'Sonstiges', 8);--> statement-breakpoint
INSERT INTO `payee`("id", "name", "system_kind") VALUES
  ('payee-opening-balance', 'Eröffnungssaldo', 'opening_balance'),
  ('payee-reconciliation', 'Korrektur Kontoprüfung', 'reconciliation_adjustment'),
  ('payee-manual-adjustment', 'Manuelle Saldokorrektur', 'manual_adjustment');--> statement-breakpoint
CREATE TRIGGER `expected_payment_version_immutable`
BEFORE UPDATE ON `expected_payment_version`
WHEN NEW."id" IS NOT OLD."id"
  OR NEW."expected_payment_id" IS NOT OLD."expected_payment_id"
  OR NEW."valid_from" IS NOT OLD."valid_from"
  OR NEW."amount_cents" IS NOT OLD."amount_cents"
  OR NEW."amount_max_cents" IS NOT OLD."amount_max_cents"
  OR NEW."currency" IS NOT OLD."currency"
  OR NEW."original_amount_cents" IS NOT OLD."original_amount_cents"
  OR NEW."note" IS NOT OLD."note"
  OR NEW."created_at" IS NOT OLD."created_at"
BEGIN
  SELECT RAISE(ABORT, 'expected_payment_version is immutable: add a new version instead');
END;
